version: "3"

networks:
  gitea:
    external: false
  drone:
    external: false

volumes:
  gitea:
    driver: local
  drone:
    driver: local

services:
  gitea:
    image: gitea/gitea:1.17.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "2222:22"

  drone:
    image: drone/drone:2
    environment:
      - DRONE_GITEA_CLIENT_ID=
      - DRONE_GITEA_CLIENT_SECRET=
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GIT_ALWAYS_AUTH=
      - DRONE_RPC_SECRET=
      - DRONE_SERVER_HOST=
      - DRONE_SERVER_PROTO=http
    restart: always
    networks:
      - drone
    volumes:
      - drone:/data
    ports:
      - "3001:80"
      - "3011:443"
