version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '192.168.42.1'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.42.1:9001'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '9001:9001'
      - '2222:2222'
    volumes:
      - '/opt/gitlab/config:/etc/gitlab'
      - '/opt/gitlab/logs:/var/log/gitlab'
      - '/opt/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
